### ISSUE TITLE
Access the request object

### ISSUE THREAD

**Issue by Sshuichi** [chatbots-pl/powerbot-messenger#5]
Hello, I would like to manipulate sessions to store data returned by the user to buid the bot logic. 
How can I access the request object on the webhook root?

**Comment by maxtomczyk** [comment]
Hi,
If I understand your request correctly, you want to access request object received directly from facebook? If so, you can use raw object passed to event handler. It’s described as rawMessage in readme.MD (table in section Server events). Please confirm if this solved your issue, you can also reach me at m.tomczyk.dev@gmail.com

**Comment by Sshuichi** [comment]
Exactly, I'll check the rawMessage and will let you know.
Thanks!

**Comment by Sshuichi** [comment]
rawMessage does not contain the context nor the request.

**Comment by maxtomczyk** [comment]
Ok,
Can you be more specific? Please provide expected output of raw message if possible. Also, from which event are you accessing raw message object?

**Comment by Sshuichi** [comment]
I'm accessing from the postback event. 
My scenario is the following: 
I want to access the session to fill all the details asked by the user to insert in my database. 
The solution I found is, access the session from the ctx object on the request_incoming event.

**Comment by maxtomczyk** [comment]
What session are you trying to access exactly? I don’t think there is session provided by Facebook, and ctx object is koa’s object, so it doesn’t have a lot to do with Messenger user. I guess you want to store data received from user between requests. If so, you need to implement it on your own, as this lib provides just messenger API integration. As not all data may be worth saving, you can check the methods called setCacheKey/getCacheKey in this file https://github.com/maxtomczyk/powerbot-cms/blob/master/modules/bot/models/User.js to check potentially (simple) solution for your problem.

**Comment by Sshuichi** [comment]
I'm using koa-redis to store the info on the session of the chat. 
I'm exploring this for the moment. Thanks for the help!

**Comment by maxtomczyk** [comment]
Ok, I think there is no problem on the side of this library. I’m closing it for now, if you have any questions feel free to contact me.
