### ISSUE TITLE
Set a constant verify_token 

### ISSUE THREAD

**Issue by Sshuichi** [chatbots-pl/powerbot-messenger#6]
At each relaunch, the verify token is different. It's hard to debug this way. 
How can we set it once for all? like in .env or something..

**Comment by maxtomczyk** [comment]
Hi again,
Randomness of verify token at each relaunch provides some security on production env. There shouldn’t be a problem while debugging it as you need verify token only to connect your app to your url. However, it can be problematic while connecting multiple apps to server. Is it your use case?

**Comment by Sshuichi** [comment]
So you need to go and set it on FB messenger App every time you restart the app. It's not convenient. 
If I'm just building the bot, I will have to restart the server a lot to see changes and each time the token resets and I need to go on Facebook and change it every single time
![image](https://user-images.githubusercontent.com/5939429/70374425-5f27cd00-190b-11ea-974c-46d7e6179de9.png)

**Comment by maxtomczyk** [comment]
You don’t have to verify your server again if your Callback url doesn’t change.

**Comment by Sshuichi** [comment]
Callback url doesn't change but verify token changes and that's the problem

**Comment by maxtomczyk** [comment]
No. Verify token is used only to validate connection once. It’s not verified for each request, just once, at the moment of saving url.

**Comment by Sshuichi** [comment]
Aha! Interesting! I thought it's checked at each request. 
I think it makes sense thanks for the clarification

**Comment by maxtomczyk** [comment]
No problem. I guess it’s not a big problem to revering your server once per 8 hours (free ngrok session time limit, which you are probably using)

**Comment by Sshuichi** [comment]
Yes, exactly.
