### ISSUE TITLE
Send Login Button

### ISSUE THREAD

**Issue by Sshuichi** [chatbots-pl/powerbot-messenger#7]
I want to identify the user on our servers 

`UnhandledPromiseRejectionWarning: Error: This type of button is not currently supported by Powerbot Messenger. Please use raw send option instead.`

Can you share an example on how to use the raw send? Any plans to support Login button?

**Comment by maxtomczyk** [comment]
Hi again!
Raw send option is method called `raw` in sender module. It sends json passed as argument to Facebook server. It means that you can send exact json from Facebook docs. In this case you can use json presented in Example usage section here: https://developers.facebook.com/docs/messenger-platform/reference/buttons/login/

Here is example of sending Login button as reply in message event:
```javascript
bot.on('message', async message => {
  try {
    const rawMessage = {
      recipient: {
        id: message.sender_id
      },
      message: {
        attachment: {
          type: 'template',
          payload: {
            template_type: 'button',
            text: 'Try the log in button!',
            buttons: [
              {
                type: 'account_link',
                url: 'https://www.example.com/authorize'
              }
            ]
          }
        }
      }
    }

    await message.reply.raw(rawMessage)
  } catch (e) {
    console.error(e)
  }
})
```

I think we can add Login button support in next minor update release.

**Comment by Sshuichi** [comment]
That would be amazing! thank you!

**Comment by maxtomczyk** [comment]
Hi @Sshuichi 
Buttons of type `account_link` and `account_unlink` are supported since commit 6fedc01. Not all of version v1.1.0 milestones are completed, but it will be probably released really soon (2-3 days). For now, you can test it by installing 6fedc01 commit.

I'll close it for now, but feel free to reopen this issue if you find any problem while using this buttons.
